### ISSUE TITLE
Naming convention for .parquet

### ISSUE THREAD

**Issue by samsoe** [mosscoder/mpg-horses#19]
@mosscoder 

Currently: 
```
{
  "n_chunks": 9,
  "total_rows": 12356,
  "total_size_mb": 4412.74068069458,
  "chunk_files": [
    "tiles_chunk_000.parquet",
    "tiles_chunk_001.parquet",
    "tiles_chunk_002.parquet",
    "tiles_chunk_003.parquet",
    "tiles_chunk_004.parquet",
    "tiles_chunk_005.parquet",
    "tiles_chunk_006.parquet",
    "tiles_chunk_007.parquet",
    "tiles_chunk_008.parquet"
  ]
}
```

**Comment by samsoe** [comment]
https://huggingface.co/datasets/mpg-ranch/dye-detection/raw/main/README.md

```
  data_files:
  - split: train
    path: "data/train.parquet"
  - split: test
    path: "data/test.parquet"
```
